
--Business questions

--1. Calculate the total revenue generated by the gym each month using the payments table.

SELECT SUM(amount) AS total_revenue, 
       DATE_TRUNC('month', payment_date) AS month
	   FROM payments
	   GROUP BY month
	   ORDER BY month;

--2. Identify the top 10 members who generated the highest total revenue for the gym.

SELECT m.member_id, m.name, m.gender, SUM(p.amount) AS total_revenue
FROM members m
JOIN payments p 
ON m.member_id=p.member_id
GROUP BY m.member_id, m.name, m.gender
ORDER BY total_revenue DESC
LIMIT 10;

--3. Find the membership type that generates the highest revenue for the business.

SELECT m.membership_type, SUM(p.amount) AS total_revenue
FROM members m
JOIN payments p 
ON m.member_id=p.member_id
GROUP BY  m.membership_type
ORDER BY total_revenue DESC;

--4. Determine the city with the highest number of active gym members.

SELECT city, COUNT(*) AS active_status
FROM members
WHERE membership_status='Active'
GROUP BY city
ORDER BY active_status DESC;

--5. Calculate the average payment amount for each membership type.

SELECT m.membership_type, ROUND(AVG(p.amount),2) AS avg_amount
FROM members m
JOIN payments p
ON m.member_id=p.member_id
GROUP BY m.membership_type;

--6. Identify members who have not attended any gym class despite having an active membership.

SELECT m.member_id, m.name
FROM members m
LEFT JOIN attendance a
ON m.member_id=a.member_id
WHERE a.member_id IS NULL;

--7. Find the most popular gym class based on total attendance.

SELECT class_id,  COUNT(*) AS total_attendance
FROM attendance
GROUP BY class_id
ORDER BY total_attendance DESC
LIMIT 5;

SELECT c.class_id, c.class_name, COUNT(*) AS total_attendance
FROM classes c
JOIN attendance a ON c.class_id=a.class_id
GROUP BY c.class_id, c.class_name
ORDER BY total_attendance DESC
LIMIT 5;

--8. Determine the trainer who conducts the highest number of classes.

SELECT t.trainer_id, t.trainer_name, COUNT(*) AS total_classes
FROM trainers t
JOIN classes c ON t.trainer_id=c.trainer_id
GROUP BY t.trainer_id, t.trainer_name
ORDER BY total_classes DESC
LIMIT 1;

--9. Identify members who attend the gym most frequently based on attendance records.

SELECT member_id, COUNT(*) AS total_attendance
FROM attendance
GROUP BY member_id
ORDER BY total_attendance DESC
LIMIT 1;

--10. Calculate the average number of classes attended per member.

SELECT AVG(attendance_count) 
FROM(
SELECT member_id, COUNT(*) AS attendance_count
FROM attendance
GROUP BY member_id
) AS member_attendance;

--11. Find the percentage contribution of each membership type to total revenue.

SELECT m.membership_type, SUM(p.amount) AS total_revenue,
ROUND(SUM(p.amount) * 100 / (SELECT SUM(amount) FROM payments),2) AS revenue_percentage
FROM members m
JOIN payments p ON m.member_id=p.member_id
GROUP BY m.membership_type;

--12. Determine the top 3 cities that generate the highest revenue for the gym.

SELECT m.city,SUM(p.amount) AS total_revenue
FROM members m
JOIN payments p ON m.member_id=p.member_id
GROUP BY m.city
ORDER BY total_revenue DESC
LIMIT 3;

--13. Identify trainers whose classes have the highest average attendance.

SELECT c.trainer_id, AVG(class_attendance) avg_attendance
FROM(
SELECT class_id, COUNT(*) AS class_attendance
FROM attendance
GROUP BY class_id
)a
JOIN classes c
ON c.class_id=a.class_id
GROUP BY c.trainer_id
ORDER BY avg_attendance DESC;

--14. Calculate the monthly growth in the number of new gym members.

SELECT DATE_TRUNC('month', join_date) AS month,
COUNT(member_id) AS new_members
FROM members
GROUP BY month
ORDER BY month;
